services:
  postgres:
    image: postgres:17
    container_name: properly-postgres
    environment:
      POSTGRES_DB: properly
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - properly-postgres-data:/var/lib/postgresql/data

volumes:
  properly-postgres-data: